In [1]:
import pandas as pd

In [13]:
df = pd.read_csv(r"D:\Projects\E-Commerce-Customer-Segmentation-Purchase-Prediction\Data\data.csv", encoding='latin-1')

In [8]:
rfm = pd.read_csv(r"D:\Projects\E-Commerce-Customer-Segmentation-Purchase-Prediction\Data\rfm_final.csv", encoding='latin-1')

In [14]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [19]:
# removing null values
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [21]:
# Convert types
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

In [22]:
# Create TotalAmount
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

In [23]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85

Merging the dataset

In [24]:
merged_df = df.merge(rfm, on="CustomerID", how="inner")

In [25]:
merged_df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalAmount,Recency,Frequency,Monetary,Cluster,DBSCAN_Cluster,Segment,Target
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,302,312,5288.63,1,0,High Value,1
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,302,312,5288.63,1,0,High Value,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,302,312,5288.63,1,0,High Value,1
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,302,312,5288.63,1,0,High Value,1
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,302,312,5288.63,1,0,High Value,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
406824,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,1,52,862.81,0,0,Low Value,1
406825,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,1,52,862.81,0,0,Low Value,1
406826,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,1,52,862.81,0,0,Low Value,1
406827,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,1,52,862.81,0,0,Low Value,1
406828,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,1,52,862.81,0,0,Low Value,1

In [30]:
final_df = merged_df[[
    'CustomerID',
    'InvoiceNo',
    'InvoiceDate',
    'Country',
    'Quantity',
    'UnitPrice',
    'TotalAmount',
    'Recency',
    'Frequency',
    'Monetary',
    'Cluster',
    'Segment'
]]

In [31]:
final_df

,CustomerID,InvoiceNo,InvoiceDate,Country,Quantity,UnitPrice,TotalAmount,Recency,Frequency,Monetary,Cluster,Segment
0,17850.0,536365,2010-12-01 08:26:00,United Kingdom,6,2.55,15.30,302,312,5288.63,1,High Value
1,17850.0,536365,2010-12-01 08:26:00,United Kingdom,6,3.39,20.34,302,312,5288.63,1,High Value
2,17850.0,536365,2010-12-01 08:26:00,United Kingdom,8,2.75,22.00,302,312,5288.63,1,High Value
3,17850.0,536365,2010-12-01 08:26:00,United Kingdom,6,3.39,20.34,302,312,5288.63,1,High Value
4,17850.0,536365,2010-12-01 08:26:00,United Kingdom,6,3.39,20.34,302,312,5288.63,1,High Value
...,...,...,...,...,...,...,...,...,...,...,...,...
406824,12680.0,581587,2011-12-09 12:50:00,France,12,0.85,10.20,1,52,862.81,0,Low Value
406825,12680.0,581587,2011-12-09 12:50:00,France,6,2.10,12.60,1,52,862.81,0,Low Value
406826,12680.0,581587,2011-12-09 12:50:00,France,4,4.15,16.60,1,52,862.81,0,Low Value
406827,12680.0,581587,2011-12-09 12:50:00,France,4,4.15,16.60,1,52,862.81,0,Low Value
406828,12680.0,581587,2011-12-09 12:50:00,France,3,4.95,14.85,1,52,862.81,0,Low Value

In [34]:
final_df.to_csv(r"..\Data\cleaned_data.csv", index=False)